### ISSUE TITLE
Jupyter notebook based documentation for Metrics Correlation algorithm.

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-py-ml#157]
**Is your feature request related to a problem?**

In Opensearch 2.7 release we are releasing `Metrics Correlation` Algorithm as an experimental feature. 

We want to have a step by step guideline how can we use Metrics Correlation algorithm. To achieve this we need to have a Jupter notebook for documentation like the way we crated notebook for Semantic search use case. [REF](https://opensearch-project.github.io/opensearch-py-ml/examples/demo_transformer_model_train_save_upload_to_openSearch.html)

We need to have a index in opensearch with multiple metrics data so that we can pull those metrics data and then send that to the execute api to get the results.

1. For the index of multiple metrics, we can use this [server machine dataset](https://github.com/NetManAIOps/OmniAnomaly). We need to create a csv file of the data and then ingest into index. [REF](https://github.com/dhrubo-os/opensearch-py-ml/blob/main/setup_tests.py)

2. When we have index ready then we can invoke api. More details about this API we can find [here](https://github.com/opensearch-project/documentation-website/issues/3815)
3. When we get results after invoking the metrics correlation algorithm we want to show the results of data by drawing a time series plot for better explanation. 
4.

**Comment by AlibiZhenis** [comment]
Hey. I started working on this. I have a small chunk of the SMD dataset with a 100 rows, and I wanted to clarify something. Am I supposed to add a zip version of the dataset in the git and then create an index using csv_to_opensearch() like in the [online retail analysis](https://opensearch-project.github.io/opensearch-py-ml/examples/online_retail_analysis.html)?

**Comment by dhrubo-os** [comment]
Thanks for the reply. That sounds good to me. 

Just to keep in mind, after creating the index when we pull up the data and send it to metrics correlation algorithm api, we kind of need to transpose the metrics. Because parameter of the api is `metrics` which is a list of metrics and each metrics contains the values of the same datapoints. 

Please let me know if this is clear to you. Thanks.

**Comment by AlibiZhenis** [comment]
Yes, it's clear. Thanks.

I am confused about how I should use MCorr in the notebook.

For jupyter notebooks, it seems that opensearch-py-ml needs to be installed with pip. And there's no MCorr model in the latest version installed by pip. Should I manually make an API request or is there some other way?

**Comment by dhrubo-os** [comment]
We will create a new jupyter notebook and keep it [here](https://github.com/opensearch-project/opensearch-py-ml/tree/main/docs/source/examples). Spnhix will generate the html from ipynb. 

And also we need to create another function for [execute` api](https://opensearch.org/docs/2.0/ml-commons-plugin/api/#execute)

**Comment by AlibiZhenis** [comment]
Do I need to create a function for execute API, or specifically Metrics Correlation? Also, does it need to be in ml_commons_client?

**Comment by dhrubo-os** [comment]
I think we can create a function for `execute` api. This function will take two parameters:

1. algorithm name
2. Input json 

In the function we will check if the json object is a valid object or not. If yes, then we will prepare the request like [this](https://opensearch.org/docs/2.7/ml-commons-plugin/algorithms/#example-execute-localization) or [this](https://opensearch.org/docs/2.7/ml-commons-plugin/algorithms/#example-simple-metrics-correlation) and send that to mlcommons.

idea this should be part of ml_commons_client. If you think this file is getting longer and longer we can extend this to another file.

**Comment by AlibiZhenis** [comment]
Should I create a different PR for execute API since it's a different task? Or is it okay to leave it in this one?

**Comment by AlibiZhenis** [comment]
Also, when I try to set enable_inhouse_python_model to true, I get the following error:
`
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "persistent setting [plugins.ml_commons.enable_inhouse_python_model], not recognized"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "persistent setting [plugins.ml_commons.enable_inhouse_python_model], not recognized"
  },
  "status": 400
}
`

**Comment by dhrubo-os** [comment]
> Also, when I try to set enable_inhouse_python_model to true, I get the following error: `{ "error": { "root_cause": [ { "type": "illegal_argument_exception", "reason": "persistent setting [plugins.ml_commons.enable_inhouse_python_model], not recognized" } ], "type": "illegal_argument_exception", "reason": "persistent setting [plugins.ml_commons.enable_inhouse_python_model], not recognized" }, "status": 400 }`

Which version of opensearch are you using to enable this? You need to use opensearch 2.7.0 version

**Comment by AlibiZhenis** [comment]
Another question: since we pass the metrics as a list, why do we need to populate the index with the data when we can send it immediately after extracting it from the csv?

**Comment by dhrubo-os** [comment]
> Another question: since we pass the metrics as a list, why do we need to populate the index with the data when we can send it immediately after extracting it from the csv?

Good Question. So the idea is to show an example to customer how to get data from index and then send that data to the metrics correlation api for further processing.

As we don't have any current index with data, we are extracting data from csv to put that in the index [This is a pre-processing step for the demonstration]

**Comment by dhrubo-os** [comment]
Execute API PR is merge. You can now raise PR for this Issue. Thanks for working on this.

**Comment by AlibiZhenis** [comment]
Hi. I determined that I was using OpenSearch 2.6. I followed [this](https://opensearch.org/docs/latest/install-and-configure/upgrade-opensearch/rolling-upgrade/#performing-the-upgrade) tutorial on how to upgrade the OpenSearch. But it provides everything except how to change the version of the nodes.

Can you help?

**Comment by dhrubo-os** [comment]
Are you using docker or tarball?

If you use docker:

1. You can follow [this article](https://opensearch.org/docs/2.7/install-and-configure/install-opensearch/docker/) for docker compose. 
2. In the `docker-compose.yml` file, you need provide: `image: opensearchproject/opensearch:2.7.0` instead of `image: opensearchproject/opensearch:latest` as the latest version is 2.8.0 now.

IF you use tarball, you can follow this article: https://opensearch.org/docs/2.7/install-and-configure/install-opensearch/tar/


LMK if you have any further questions. Thanks.

**Comment by AlibiZhenis** [comment]
It helped, thanks. However, there is another problem. When I try to use the data in the index for mCorr, I get the following error : `TypeError: Unable to serialize`. 

Everything just comes down to using the original pandas dataframe and converting it to a Python list. 

If the purpose of this maneuver is to demonstrate how to upload data to index, I can't help but feel that it is irrelevant to the purpose of this notebook, which is mCorr. Perhaps, there should be another notebook which demonstrates how to upload data to index?

Also, even when I convert the pandas dataframe to list and use it for mCorr, I get the following error: "ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))".

I made sure to put "plugins.ml_commons.enable_inhouse_python_model" to true and the dataset has much less than 10000 cells. I wonder why it is timing out.

**Comment by dhrubo-os** [comment]
Sorry I missed your comment.

Can you please check [here](https://github.com/opensearch-project/opensearch-py-ml/blob/main/setup_tests.py#L47-L85) how to insert data?

May be we can add corresponding code here to create that index? I agree that, In demo we don't need to show how to create index and insert values to the index.

Looks like your read time out is very small just 10 seconds. Can you try to increase the read timeout and then check?

Please lmk if you have any other question. Thanks

**Comment by AlibiZhenis** [comment]
Increasing the timeout didn't help. Turns out the problem is elsewhere. Error starts with the Failed to register model.

`
opensearch-node1       | [2023-06-23T04:00:24,287][ERROR][o.o.m.a.r.TransportRegisterModelAction] [opensearch-node1] Failed to register model
opensearch-node1       | org.opensearch.transport.RemoteTransportException: [opensearch-node2][172.18.0.2:9300][cluster:admin/opensearch/mlinternal/forward]
opensearch-node1       | Caused by: java.lang.IllegalStateException: Message fully read (request) but more data is expected for requestId [1438], action [cluster:admin/opensearch/mlinternal/forward]; resetting
opensearch-node1       |        at org.opensearch.transport.InboundHandler.newRequest(InboundHandler.java:286) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:242) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:132) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:114) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:769) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) [opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) [transport-netty4-client-2.7.0.jar:2.7.0]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) [netty-handler-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383) [netty-handler-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246) [netty-handler-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295) [netty-handler-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) [netty-codec-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.91.Final.jar:4.1.91.Final]
opensearch-node1       |        at java.lang.Thread.run(Thread.java:833) [?:?]
opensearch-node1       | Caused by: java.io.EOFException
opensearch-node1       |        at org.opensearch.common.io.stream.InputStreamStreamInput.readByte(InputStreamStreamInput.java:76) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.common.io.stream.StreamInput.readInt(StreamInput.java:205) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.common.io.stream.FilterStreamInput.readInt(FilterStreamInput.java:70) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.ml.common.model.TextEmbeddingModelConfig.<init>(TextEmbeddingModelConfig.java:115) ~[?:?]
opensearch-node1       |        at org.opensearch.ml.common.transport.register.MLRegisterModelInput.<init>(MLRegisterModelInput.java:104) ~[?:?]
opensearch-node1       |        at org.opensearch.ml.common.transport.forward.MLForwardInput.<init>(MLForwardInput.java:63) ~[?:?]
opensearch-node1       |        at org.opensearch.ml.common.transport.forward.MLForwardRequest.<init>(MLForwardRequest.java:43) ~[?:?]
opensearch-node1       |        at org.opensearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:85) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.newRequest(InboundHandler.java:282) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:242) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:132) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:114) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:769) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-2.7.0.jar:2.7.0]
opensearch-node1       |        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) ~[transport-netty4-client-2.7.0.jar:2.7.0]

`

**Comment by dhrubo-os** [comment]
> 

Can you please tell me the steps to reproduce the issue in my end?

What request did you send to the cluster?

**Comment by AlibiZhenis** [comment]
I am using OS 2.7 and I already set all of the settings. You can see the notebook [here](https://github.com/AlibiZhenis/opensearch-py-ml/blob/mCorr_example/docs/source/examples/demo_metrics_correlation.ipynb).

**Comment by dhrubo-os** [comment]
Hmm, I just ran your notebook and I was able to get output:

```
{'function_name': 'METRICS_CORRELATION',
 'output': {'inference_results': [{'event_window': [2.0, 94.0],
    'event_pattern': [0.1628726,
     0.17291103,
     0.1650779,
     0.14422576,
     0.11990736,
     0.09729365,
     0.08097533,
     0.07199156,
     0.069429845,
     0.07270392,
     0.08256483,
     0.100011915,
     0.123968534,
     0.14978369,
     0.172563,
     0.18076012,
     0.17145781,
     0.14817542,
     0.12038838,
     0.09797756,
     0.08960859,
     0.0955576,
     0.11185043,
     0.1305059,
     0.14417115,
     0.14867531,
     0.14488932,
     0.1381247,
     0.13548608,
     0.1444314,
     0.16681594,
     0.20365955,
     0.25175068,
     0.318763,
     0.3899008,
     0.45330656,
     0.5011714,
     0.5278945,
     0.53014517,
     0.5062867,
     0.45027298,
     0.4456686,
     0.4209662,
     0.3885302,
     0.35869372,
     0.3340211,
     0.31001395,
     0.28004783,
     0.24047157,
     0.19322377,
     0.15334718,
     0.11692931,
     0.08834231,
     0.0681265,
     0.054135274,
     0.043827217,
     0.036045555,
     0.031724166,
     0.0334834,
     0.04476927,
     0.06946544,
     0.105409704,
     0.14753862,
     0.18693998,
     0.21311778,
     0.21818613,
     0.20075372,
     0.16648816,
     0.13061278,
     0.09916867,
     0.07933296,
     0.07126698,
     0.07225353,
     0.07784651,
     0.0839629,
     0.09038916,
     0.09414779,
     0.09750935,
     0.104938634,
     0.12241115,
     0.15522149,
     0.20462656,
     0.26510087,
     0.3271752,
     0.3735341,
     0.38837066,
     0.367913,
     0.3273447,
     0.27416316,
     0.22305399,
     0.18449467,
     0.16176929,
     0.15200222,
     0.14995821,
     0.15202914,
     0.15801252,
     0.17027178,
     0.19150288,
     0.21942082],
    'suspected_metrics': [2,
     3,
     6,
     10,
     15,
     18,
     19,
     20,
     21,
     24,
     27,
     29,
     30,
     32,
     34,
     35]}]}}
```

**Comment by AlibiZhenis** [comment]
I was able to get the same result after avoiding the upload data to index part. I will raise a PR soon.

**Comment by AlibiZhenis** [comment]
There is one more problem. The result of the model is not accurate. The actual event window is [86, 99], while the prediction is [2, 94]. Should I proceed with the notebook?

**Comment by dhrubo-os** [comment]
> I was able to get the same result after avoiding the upload data to index part. I will raise a PR soon.

You mean without executing `Cell 16`? 

```
# Creating and populating an index with the dataset
df = oml.pandas_to_opensearch(df_pd_transposed,
                    os_client=client,
                     os_dest_index='smd',
                    os_if_exists="replace",
                    os_refresh=True,)
```

This section?

I was able to create an index (`smd`) with your notebook. What problem were you facing there?

**Comment by dhrubo-os** [comment]
> There is one more problem. The result of the model is not accurate. The actual event window is [86, 99], while the prediction is [2, 94]. Should I proceed with the notebook?
> 
> You can see the ground truth in the Y variable.

IF you think you are covering all the steps I outlined above, please raise a PR. There could be some data quality issue to feed into the model, we can look into this in details after raising your PR.

**Comment by AlibiZhenis** [comment]
Sorry for the wait. PR is raised.
